title: Biased SD Video Generation
description: Research site for measuring & mitigating visual drift in diffusion pipelines.
theme: jekyll-theme-cayman

url: "https://ajiteshbankulaa.github.io"
baseurl: "/BiasedSDVideoGeneration"

github:
  repository_url: "https://github.com/ajiteshbankulaa/BiasedSDVideoGeneration"
  owner_url: "https://github.com/ajiteshbankulaa"
